### PR TITLE
Updates to specification of Ternary use.

### PR DESCRIPTION
**Pull request by robotpistol**
* Add a suggestion for avoiding multiple conditionals in ternary statements
* Add examples for avoiding multiple conditionals in statements
* Add examples for avoiding mutli-line ternary statements

### CODE REVIEW

**Comment by BMorearty** [comment]
These seem like reasonable suggestions...but IMO, not worth including in the style guide. (I've been thinking it would be awesome if we try to limit rules to the most important ones, in the interest of keeping the guide from getting unwieldy.)

**Comment by robotpistol** [comment]
You make a reasonable point.  My main intent was to add examples for an item already in the style guide about discouraging multi-line ternaries.  I don't mind dropping the section for multiple clauses (though I think they should also be discouraged)

**Comment by BMorearty** [comment]
:+1: to dropping the section for multiple clauses. I don't think the examples are necessary for the other one but I don't object if folks think they are.

**Comment by tommydangerous** [comment]
Close PR?

**Comment by robotpistol** [comment]
I'm gonna fix this up slightly still feel strongly about multi line ternaries

**Comment by robotpistol** [comment]
Ok, updated this PR.  I think that multi line ternaries and complex ternary conditionals negatively impact code.  They should be used sparingly.

I  do think that a number of the examples are redundant and unnecessarily didactic.
PTAL

**Comment by ljharb** [comment]
LGTM if @BMorearty agrees

**Comment by tommydangerous** [comment]
LGTM, I like.

**Comment by BMorearty** [comment]
Ok :+1:

**Pull request merged**
