### PR TITLE
[private definition] Add a new line between private/protected and method definition

### PR DESCRIPTION
**Pull request by tommydangerous**
We should add a new line between `private` and `protected` and the method definition underneath it.

Example:
```
class Person

  def age
  end

  protected

  def dob
  end
end
```

### CODE REVIEW

**Comment by BMorearty** [comment]
If we're going to change the example, we'd better also change the wording above the example. The wording says leave one blank line _above_ but not below.

I'm in favor of this change (if the wording is changed too) but I'm fine with leaving it as is, too. I've forced myself to get used to it.

**Comment by tommydangerous** [comment]
Updated the wording of the example to include below as per direction.

**Comment by BMorearty** [comment]
I'm good with this change.

**Comment by robotpistol** [comment]
LGTM

**Comment by jasonkb** [comment]
Haha I don't understand why there is positive sentiment around this while there is negative sentiment around wanting "private" and friends to be indented one space less.

I personally supported both endeavours.

**Comment by tommydangerous** [comment]
Why is this closed? I haven't made the change yet :(

**Comment by BMorearty** [comment]
That was a mistake! Sorry.

**Comment by BMorearty** [comment]
I blame jetlag

**Comment by tommydangerous** [comment]
Glad you made it to Paris safely!

**Pull request merged**
