### PR TITLE
Adding links to rules

### LINKED ISSUE #75: Link to rule
One of the awesome things about bbatsov's guide is that each rule is accompanied by a link to that particular rule, so that you can easily reference it in a discussion. We should do the same thing here!

### PR DESCRIPTION
**Pull request by venantius**
Resolves #75

### CODE REVIEW

**Comment by venantius** [comment]
(man, was this boring)

**Comment by BMorearty** [comment]
Spot-tested by going to https://github.com/airbnb/ruby/tree/link-to-rule and clicking a few of them. It was so boring. :stuck_out_tongue: Seems to work, although some of the large sections at the beginning are missing a link (maybe because they are implicitly linked because they are headers).

Speaking of headers, turning every rule into a `####`-style header seems like an easier way to do it. But I haven't tried it. Maybe it wouldn't look good.

**Comment by tommydangerous** [comment]
:+1:

**Comment by venantius** [comment]
Per #75, I'm going to assume this isn't contentious and am going to merge now.

**Pull request merged**
