### PR TITLE
chinese version

### PR DESCRIPTION
**Pull request by 1c7**

### CODE REVIEW

**Comment by chengyin** [comment]
Hi there! Thank you for the translation. This is fantastic! 👍🏼

Some suggestions:

1. Can we use the proper Chinese punctuations instead of the English ones?
2. For the [comment section](https://github.com/1c7/ruby-airbnb#文件类-级别的注释-fileclass-level-comments) I am not sure if the example comments in the code needs to be translated
3. I recommend use 正确 and 错误 instead of 不好 and 好

Let me know what do you think. Glad to help if you have any questions. Once again, thank you for the great work!

**Comment by 1c7** [comment]
@chengyin 
1. Sure, no problem, I would replace these English puncations to Chinese
2. I think you are right, let me turn that back to English, comment is not really necessary to translate
3. Sure. 

:D

**Comment by 1c7** [comment]
@chengyin  @ljharb  Done.
:D

**Comment by chengyin** [comment]
Thank you!

**Comment by 1c7** [comment]
@chengyin  :D

**Pull request merged**
