### PR TITLE
Add example against {} in multiline block

### PR DESCRIPTION
**Pull request by conzjiang**
couldn't figure out how to modify this patch https://github.com/airbnb/ruby/pull/98 for some reason :/

this pr keeps the correct examples grouped together, while adding a new example (see #98 for more details)

@kmsun07

### CODE REVIEW

**Comment by kmsun07** [comment]
LGTM. not related to the code we care about, but it's a little weird to do `puts` and `print` interleaved, right?

**Comment by conzjiang** [comment]
@kmsun07 I use `print` when I'm printing out a newline because it looks strange to me to have a blank `puts` on one line.

```ruby
puts name
puts
puts "..."
```

If it's not in line with our style guide though, I can change it!

**Comment by BMorearty** [comment]
LGTM too, but I agree with @kmsun07. Doing `print "\n"` seems really strange to me, even more so when mixed with a call to `puts`.

I don't think it's specified in the style guide. It's just what I think most people do.

**Comment by kmsun07** [comment]
this isn't really relevant to the style guide; print/puts is rarely present in a production web app

that said, maybe if we just changed it to
```
puts 'line 1'
puts 'line 2'
```
it would be fine? the goal is just to not detract from the main purpose of the example, so the less 'interesting' the contents, the better

**Comment by conzjiang** [comment]
@kmsun07 Makes sense! 😄  just made the change, i'll merge if the new change looks good to you

**Comment by conzjiang** [comment]
@kmsun07 @BMorearty Makes sense! 😄  just made the change, i'll merge if the new change looks good to yall

**Comment by kmsun07** [comment]
👍

**Comment by BMorearty** [comment]
👍

**Comment by conzjiang** [comment]
merged #100

**Pull request merged**
