### PR TITLE
Add symbols as valid class names

### PR DESCRIPTION
**Pull request by tomprats**
Allows symbols to be used as class names

https://github.com/airbnb/ruby/issues/159

### CODE REVIEW

**Comment by tomprats** [comment]
@ljharb Was hoping to get your thoughts on this when you get a chance

**Comment by ljharb** [comment]
@tomprats it’d need the thoughts of a current airbnb employee on whether this is a style they want to allow.

**Comment by BMorearty** [comment]
@tomprats Thanks for the PR. What's the rationale for the change?

My inclination is to stick with just strings for consistency but I'd like to hear your reasoning first.

**Comment by tomprats** [comment]
@BMorearty I originally had been using the class until I found out why that was bad. When I was going through fixing things, it just seemed more natural to do `class_name: :Taco` than to do `class_name: "Taco"`

It seemed similar to how we used to do `"hey" => "you"` but now would do `hey: :you` or `hey: "you"` (depending on what's valid or where it was used). Since in this case both strings and symbols are accepted, I thought the rule could allow them as well

**Comment by BMorearty** [comment]
Yeah, I can understand that reasoning. But since both strings and symbols work and we've already been standardizing on strings, let's stick with just strings. Also in the Rails code I've seen, strings are what's typically used when referencing a class by name.

**Comment by tomprats** [comment]
Sounds good. Thanks for taking a look at it guys!

**Pull request closed without merging**
