### PR TITLE
[collections] Add a trailing comma to an array

### PR DESCRIPTION
**Pull request by tommydangerous**
Add a comma to the last element in the array.

### CODE REVIEW

**Comment by robotpistol** [comment]
:+1: from me.  I think we're already usually calling for this.  I don't it's necessary for arrays on a single line
```ruby
# good
[1, 2, 3]

# good
[
  1,
  2,
  3,
]
```

**Comment by tommydangerous** [comment]
K, I'll update it to show what you just wrote.

**Comment by BMorearty** [comment]
:+1:

**Comment by romanfuchs** [comment]
:+1:

**Pull request merged**
